name: "Image push release"
on:
  push:
    tags:
      - v*
jobs:
  image-build-push:
    name: Image build and push
    runs-on: linux-amd64-cpu4
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Go Proxy
        id: setup-go-proxy
        uses: nv-gha-runners/setup-artifactory-go-proxy@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to nvstaging container registry
        uses: docker/login-action@v3
        with:
          registry: nvcr.io/nvstaging/mellanox
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_TOKEN }}
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: nvcr.io/nvstaging/mellanox/k8s-launch-kit
      - name: Build and push container image
        uses: docker/build-push-action@v6
        env:
          GOPROXY: ${{ steps.setup-go-proxy.outputs.goproxy-url || 'direct' }}
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            nvcr.io/nvstaging/mellanox/k8s-launch-kit:${{ github.ref_name }}
          labels: ${{ steps.docker_meta.outputs.labels }}
